[pytest]

;更加规范+约束：定义用例的收集目录，以及用例模块、类、方法的匹配规则
testpaths = testcases/
python_files = test_*.py
python_classes = Test*
python_functions = test_*



;pytest默认对未声明的marker只是Warning不会中断执行；只有开启--strict-markers后，未注册的marker才会报错
;建议开启：如果不开启，可能会导致一些marker未定义的Warning发现不了，实际用例没有执行，而且定义标签也很乱
addopts = --strict-markers